<div class="panels__item panels__item__origin--more" data-page='origin-more' data-module='origin'>
    <div class="panel__head">
        页面配置 > 原创作品 - 更多
    </div>
    <div class="panel__body panel__body__showcase">
      <ul class="showcase__list">
      <li class="showcase__item showcase__item__add" data-module='origin'>
        {% include "__addshowcase.swig"%}
      </li>
      </ul>
      {# <div class="showmore">查看更多</div> #}
    </div>
</div>
