<div class="panels__item panels__item__vfx--more" data-page='vfx-more' data-module='vfx'>
    <div class="panel__head">
        页面配置 > 动画作品 - 更多
    </div>
    <div class="panel__body panel__body__showcase">
      <ul class="showcase__list">
        <li class="showcase__item showcase__item__add" data-module='vfx'>
          {% include "__addshowcase.swig"%}
        </li>
      </ul>
      {# <div class="showmore" data-page='1' data-module='vfx'>查看更多</div> #}
    </div>
</div>
