<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <title>多宝树影视科技-管理后台</title>
        <link rel="stylesheet" href="/styles/admin.css">
        <script src="/js/libs/jquery.min.js"></script>
    </head>
    <body>
        <div class="window">
        {%include "./part/admin/main.swig"%}
        </div>
    </body>
</html>
