<div class="tts__footer">
    <a href="/" class="footer__link">
        <i class="tts__icon tts__icon__copy"></i>
        Treasure Tree Studios All Rights Reserved.
    </a>
    <div style="width:300px;margin:0 auto; padding-top:10px;">
    	<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802021997" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="/images/ba.png" style="float:left;margin-right:5px;"/>京公网安备 11010802021997号</a>
    </div>
</div>
