<div class="index__vfx">
    <div class="vfx__head">
        <div class="head__more">
            <p class="more__title">{{more.title}}</p>
            <p class="more__subtitle">{{more.subtitle}}</p>
            {%if more.more%}
            <div class="more__link">
                <p class='link__title'>更多</p>
                <p class="link__subtitle">more</p>
            </div>
            {%endif%}
        </div>
    </div>
</div>
